apiVersion: v1
kind: Namespace
metadata:
  name: covjabnoti
  labels:
    name: covjabnoti

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: covjabnoti
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: covjabnoti
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: covjabnoti
  namespace: covjabnoti
spec:
  selector:
    app: covjabnoti
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covjabnoti
  namespace: covjabnoti
spec:
  selector:
    matchLabels:
      app: covjabnoti
  replicas: 1
  template:
    metadata:
      labels:
        app: covjabnoti
    spec:
      containers:
      - name: covjabnoti
        image: csaman10/covjabnoti:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080